### ISSUE TITLE
bug! onTapListener gets a ScreenCoordinate which should be in pixel units but its giving in longitude and latitude units instead!

### ISSUE THREAD

**Issue by ember11498** [mapbox/mapbox-maps-flutter#190]
i want to use ScreenBox to queryfeatures i was using onTapListener to know where the user taps on the screen, unfortunately it seems there is a bug and ScreeCoordinates are actual map coordinates instead of pixel coordinates!

**Comment by evil159** [comment]
This should be addressed by https://github.com/mapbox/mapbox-maps-flutter/pull/473

**Comment by noforeignland** [comment]
This is still a problem in April 2024 - is #473 pull request going to be merged in the next realese?

**Comment by maios** [comment]
We believe this issue has been fixed in our recent releases. Please update to the latest version and verify if the problem persists.

Additionally, since version 2.9.0, we’ve introduced the Interactive Maps Element API. We encourage you to use this API to add interaction to a map, layer, or other elements. Documentations can be found [here](https://docs.mapbox.com/flutter/maps/guides/user-interaction/interactions/)

This ticket will now be closed. If you continue to experience any issues, feel free to reopen it. Thank you!
