### ISSUE TITLE
Black screen (offline map)

### ISSUE THREAD

**Issue by NaimAbb** [mapbox/mapbox-maps-flutter#661]
I have a problem, which is that I am trying to view the map without connecting to the Internet, and I followed the example on github, but after downloading the map, the screen remains black.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-21 at 20 59 40](https://github.com/user-attachments/assets/57ceae20-f8d6-412e-8774-f9dea5a58321)

**Comment by vigin-hsa** [comment]
me too have this problem..please let me know once any fix is given or if you find some ways to make this work

**Comment by maios** [comment]
Hi, could you try running it on fresh install app? If it still persists then could you share the `map_data.db` from the device?

**Comment by vigin-hsa** [comment]
i tried..doesnt work
attaching map_data.db

**Comment by vigin-hsa** [comment]
@maios Please let me know the status

**Comment by NaimAbb** [comment]
> Hi, could you try running it on fresh install app? If it still persists then could you share the `map_data.db` from the device?

I noticed that when downloading it as satellite style, the screen remains black, and when choosing another style type, the map appears

**Comment by maios** [comment]
> > Hi, could you try running it on fresh install app? If it still persists then could you share the `map_data.db` from the device?
> 
> I noticed that when downloading it as satellite style, the screen remains black, and when choosing another style type, the map appears

@NaimAbb Satellite style or anything that uses raster tiles need to have correct pixelRatio, which in this https://github.com/mapbox/mapbox-maps-flutter/pull/640 it should use the default pixelRatio, this fix is included in v2.2.0, can you try with this version, fresh install app and see if it works?

**Comment by maios** [comment]
> Any updates for this issue? We rely on offline maps and it's not working for us either.

Could you provide MapboxMaps Flutter SDK version that you are using, additionally a small project to help reproduce would be helpful for us to debug this issue?

**Comment by vigin-hsa** [comment]
Hi I am using latest version of mapbox..
Example project in mapbox package itself is not working..
Can you please check as our project is relying on this offline feature

**Comment by maios** [comment]
the example in our package works for us :-/ so I suspect this might be caching issues, but fresh install should then work. Maybe you can provide a small projects that can reproduce the issue, for more information like devices name and model?

**Comment by noforeignland** [comment]
We are seeing the same problem.

To test, I do the following:
1) Delete the demo app from the device to remove all cached files.
2) Run the demo app, and download the map tiles in the offline demo.
3) When the demo completes a blank map is presented - no map details are available at all.

Points to note:
1) Map appears to display only the background terrain colour - zooming in and panning around reveals no detail.
2) Tested on OnePlus 10 (Android 11) and iPhone (14 Pro, iOS 17.5.1)
3) Using the latest available version: mapbox_maps_flutter: 2.1.0
4) Tested with various map styles (have tried using MAPBOX_STREETS, DARK, SATELLITE and our own custom style URLs)

**Comment by noforeignland** [comment]
> > Any updates for this issue? We rely on offline maps and it's not working for us either.
> 
> Could you provide MapboxMaps Flutter SDK version that you are using, additionally a small project to help reproduce would be helpful for us to debug this issue?

There's no need to provide a demo project. The mapbox demo app displays this behaviour on both our physical test devices, as noted in my earlier comment. I've also added similar code to our own app but this fails too. Can you share more info about what devices / environment you see this working on?

**Comment by noforeignland** [comment]
> our apologies, it turns out that we did not include #640 which supposed to fix offline map for raster tiles in our latest release. We will be issuing new patch release asap and hope it will fix the black offline map for you <3

Thanks - will this also fix the problem we're seeing with vecor tiles? Note above, that no layers raster or vecror work for us.

**Comment by baleboy** [comment]
I have just tested it by building the examples from main and running on iPhone 15 Pro / iOS 18.1 Beta:
- launch the examples app
- open Offline example
- click "Download map" and wait for "Style Pack" and "Tile region" to reach 1.0
- map shows
- enable airplane mode and pan around
- map continues to show

**Comment by vigin-hsa** [comment]
can you please try in android

**Comment by baleboy** [comment]
> can you please try in android

I could only try this on the emulator with similar result. I'll continue testing

**Comment by noforeignland** [comment]
I have been testing and seeing the problem desceribed on two physical devices as noted yesterday. One iOS and the other Android.

**Comment by baleboy** [comment]
I can also confirm that the issue reproduces in my set-up with the stock example built with 2.2.0, so the upcoming 2.2.1 or building from the main branch should resolve the issue at least partially as expected. If the example works with the latest version but your own application doesn't, then we would appreciate if you could share a reproducer.

**Comment by baleboy** [comment]
we just released 2.2.1 that should resolve this issue

**Comment by noforeignland** [comment]
This issue is not fixed. 

I have just cloned the lastest repo and your demo still fails with a black screen after the map has downloaded.

This is you demo running on my on OnePlus 10 (Android 11):  https://youtu.be/u5rPyy_uF4g

**Comment by baleboy** [comment]
Thanks for the video, it's helpful. I can see that the map shows when you return to the offline example the second time. Is this the same behavior you have observed previously? I was under the impression that the map stayed black no matter what.

**Comment by noforeignland** [comment]
> Is this the same behavior you have observed previously?


No this is not the behaviour I saw previously. 

I was seeing what I think is the background color for the map style I had downloaded - a different issue from the black screen perhaps? Maybe we are addressing multiple bugs with this ticket?

See my comment from 4 days ago for my description on how to reproduce the problem and the map's appearance:



> To test, I do the following:
> 
- > Delete the demo app from the device to remove all cached files.
- > Run the demo app, and download the map tiles in the offline demo.
- > When the demo completes a blank map is presented - no map details are available at all.
> Points to note:
> 
- > Map appears to **display only the background terrain colou**r - zooming in and panning around reveals no detail.
- > Tested on OnePlus 10 (Android 11) and iPhone (14 Pro, iOS 17.5.1)
- > Using the latest available version: mapbox_maps_flutter: 2.1.0
- > Tested with various map styles (have tried using MAPBOX_STREETS, DARK, SATELLITE and our own custom style URLs)

**Comment by baleboy** [comment]
I think this might be a separate issue, possibly Android specific. I can reproduce on Galaxy S24 but not iPhone 15 Pro

**Comment by noforeignland** [comment]
I see exactly the same problem on iOS (tested on physical device iPhone 14 Por, iOS 17.5.1) so this is not Android specific:

https://youtu.be/r7NJGsc8v1c

**Comment by baleboy** [comment]
Reopening given the latest reports.

**Comment by noforeignland** [comment]
> @noforeignland it seems that the problem is with the TileStore created at a temporary directory, we are investigating this. Using `TileStore.createDefault()` should work so can you try with default TileStore and see if the black offline map goes away?

Please note my comments and video links for Android and iOS attached above. We are not seeing a black map, we are seeing a map in what appears to be the style's base color which might be a different problem.

**Comment by maios** [comment]
@noforeignland by "style's base color", do you mean this? Because then it is the same problem where the tiles are not loaded 😅 
<img width="486" alt="image" src="https://github.com/user-attachments/assets/b0c2f06e-a256-4b9f-990b-5d0407a975b2">

**Comment by maios** [comment]
Hi everyone, we have updated our offline example, could you please try again and report to us if the black offline map still exist? It would be a good idea to also clearing Derived data before building the app from fresh install.

**Comment by noforeignland** [comment]
> Hi everyone, we have updated our offline example, could you please try again and report to us if the black offline map still exist? It would be a good idea to also clearing Derived data before building the app from fresh install.

Our inital tests look good. Thanks for working on this.
